"""add profile_snapshot to runs

Revision ID: 116ac14ba6d6
Revises: 9049b6c4b524
Create Date: 2026-02-02 11:30:50.249312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '116ac14ba6d6'
down_revision: Union[str, Sequence[str], None] = '9049b6c4b524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prompt_version', 'prompt_versions', ['prompt_id', 'version_number'])
    op.drop_constraint(op.f('prompt_versions_base_profile_id_fkey'), 'prompt_versions', type_='foreignkey')
    op.drop_column('prompt_versions', 'base_profile_id')

    # 기존 runs/run_results 데이터 삭제 (테스트 데이터만 있으므로)
    op.execute("DELETE FROM run_results")
    op.execute("DELETE FROM runs")

    # profile_snapshot 컬럼 추가 (NOT NULL)
    op.add_column('runs', sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'profile_snapshot')
    op.add_column('prompt_versions', sa.Column('base_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('prompt_versions_base_profile_id_fkey'), 'prompt_versions', 'evaluator_profiles', ['base_profile_id'], ['id'])
    op.drop_constraint('uq_prompt_version', 'prompt_versions', type_='unique')
    # ### end Alembic commands ###
